# Generated by Django 2.2.24 on 2021-12-22 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20211209_1839'),
        ('mainapp', '0007_auto_20211220_0025'),
    ]

    operations = [
    ]
