# Generated by Django 2.2.24 on 2021-12-19 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0006_auto_20211220_0025'),
        ('authnapp', '0006_auto_20211215_2347'),
    ]

    operations = [
    ]
