# Generated by Django 2.2.24 on 2021-12-09 18:39

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0007_auto_20211206_1752"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 12, 11, 18, 39, 20, 908021, tzinfo=utc),
                verbose_name="актуальность ключа",
            ),
        ),
    ]
