# Generated by Django 2.2.24 on 2021-12-22 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0007_merge_20211219_2151'),
        ('authnapp', '0002_auto_20211122_1755'),
        ('authnapp', '0008_auto_20211209_1839'),
    ]

    operations = [
    ]
